express   = require('express')
path      = require('path')
api       = require('./lib/api')
scripts   = require('./lib/scripts/index')
passport  = require('./config/passport')
app       = module.exports = express()

app.set('port', process.env.PORT || 3000)
app.set('views', __dirname + '/views')
app.use(express.logger('dev'))
app.use(express.bodyParser())
app.use(express.methodOverride())
app.use(express.cookieParser())
app.use(express.session({ secret: "alkjdljasdjvfnvakjlshduiehfa" }))
app.use(passport.initialize())
app.use(passport.session())
app.use(express.compress())
app.use(api)
app.use(scripts)
app.use(express.static(path.join(__dirname, '../build')))
app.use(app.router)

if ('development' == app.get('env'))
  app.use(express.errorHandler())

